# Generated by Django 4.1.7 on 2023-03-21 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_fr', models.CharField(max_length=50, null=True)),
                ('name_en', models.CharField(max_length=50, null=True)),
                ('name_ar', models.CharField(max_length=50, null=True)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='category_images/')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('symbol', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ordered', models.DateTimeField(auto_now_add=True)),
                ('token', models.CharField(blank=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=255)),
                ('address', models.TextField(null=True)),
                ('city', models.CharField(max_length=255)),
                ('payment_method', models.CharField(max_length=255, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('complete', models.BooleanField(default=False)),
                ('delivered', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date_ordered'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_fr', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_ar', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('status', models.CharField(choices=[('Hot', 'Hot'), ('Sale', 'Sale'), ('New', 'New')], default='New', max_length=255)),
                ('status_fr', models.CharField(choices=[('Hot', 'Hot'), ('Sale', 'Sale'), ('New', 'New')], default='New', max_length=255, null=True)),
                ('status_en', models.CharField(choices=[('Hot', 'Hot'), ('Sale', 'Sale'), ('New', 'New')], default='New', max_length=255, null=True)),
                ('status_ar', models.CharField(choices=[('Hot', 'Hot'), ('Sale', 'Sale'), ('New', 'New')], default='New', max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('description_fr', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_ar', models.TextField(blank=True, null=True)),
                ('product_details', models.TextField(blank=True)),
                ('product_details_fr', models.TextField(blank=True, null=True)),
                ('product_details_en', models.TextField(blank=True, null=True)),
                ('product_details_ar', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_fr', models.CharField(max_length=50, null=True)),
                ('name_en', models.CharField(max_length=50, null=True)),
                ('name_ar', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_fr', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_ar', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_fr', models.CharField(max_length=100, null=True)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('name_ar', models.CharField(max_length=100, null=True)),
                ('value', models.CharField(max_length=100, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.propertytype')),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1)),
                ('title', models.CharField(default='', max_length=255)),
                ('content', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='app.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('key_fr', models.CharField(max_length=255, null=True)),
                ('key_en', models.CharField(max_length=255, null=True)),
                ('key_ar', models.CharField(max_length=255, null=True)),
                ('value', models.CharField(max_length=255)),
                ('value_fr', models.CharField(max_length=255, null=True)),
                ('value_en', models.CharField(max_length=255, null=True)),
                ('value_ar', models.CharField(max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informations', to='app.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='properties',
            field=models.ManyToManyField(to='app.property'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='app.tag'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('properties', models.ManyToManyField(to='app.property')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_url', models.CharField(blank=True, max_length=255)),
                ('website_name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, upload_to='website_images/')),
                ('logo_white', models.ImageField(blank=True, upload_to='website_images/')),
                ('favicon', models.FileField(blank=True, upload_to='website_images/')),
                ('description', models.TextField(blank=True)),
                ('description_fr', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_ar', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True)),
                ('keywords_fr', models.TextField(blank=True, null=True)),
                ('keywords_en', models.TextField(blank=True, null=True)),
                ('keywords_ar', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('support_phone', models.CharField(blank=True, max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('address_fr', models.CharField(blank=True, max_length=255, null=True)),
                ('address_en', models.CharField(blank=True, max_length=255, null=True)),
                ('address_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('instagram', models.CharField(blank=True, max_length=255)),
                ('facebook', models.CharField(blank=True, max_length=255)),
                ('tiktiok', models.CharField(blank=True, max_length=255)),
                ('whatsapp', models.CharField(blank=True, max_length=255)),
                ('exchangerate_api', models.CharField(blank=True, max_length=255)),
                ('smtp_host', models.CharField(blank=True, max_length=255)),
                ('smtp_port', models.IntegerField(default=465)),
                ('smtp_username', models.CharField(blank=True, max_length=255)),
                ('smtp_password', models.CharField(blank=True, max_length=255)),
                ('smtp_SSL', models.BooleanField(default=True)),
                ('email_recivers', models.TextField(blank=True)),
                ('telegram_bot_api', models.CharField(blank=True, max_length=255)),
                ('telegram_recivers', models.TextField(blank=True)),
                ('paypal_public_key', models.CharField(blank=True, max_length=512)),
                ('paypal_secret_key', models.CharField(blank=True, max_length=512)),
                ('paypal_sandbox', models.BooleanField(default=False)),
                ('cmi_merchant_id', models.CharField(blank=True, max_length=512)),
                ('cmi_secret_key', models.CharField(blank=True, max_length=512)),
                ('cmi_sandbox', models.BooleanField(default=False)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.currency')),
            ],
        ),
    ]
