# Generated by Django 4.1.7 on 2023-03-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='keywords',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='keywords_ar',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='keywords_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='keywords_fr',
            field=models.TextField(null=True),
        ),
    ]
