# Generated by Django 4.1.7 on 2023-03-21 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_configuration_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='address_ar',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='address_en',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='address_fr',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='keywords_ar',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='keywords_en',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='keywords_fr',
        ),
    ]
