# Generated by Django 4.1.7 on 2023-03-21 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_configuration_address_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='address_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='address_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='address_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='keywords_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='keywords_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='keywords_fr',
            field=models.TextField(null=True),
        ),
    ]
