# Generated by Django 4.1.7 on 2023-03-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_tag_product_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='currency',
            field=models.CharField(choices=[('MAD', 'MAD'), ('USD', 'USD'), ('EUR', 'EUR')], default='MAD', max_length=255),
        ),
        migrations.AddField(
            model_name='configuration',
            name='currency_symbol',
            field=models.CharField(choices=[('MAD', 'MAD'), ('USD', 'USD'), ('EUR', 'EUR')], default='MAD', max_length=255),
        ),
    ]
