# Generated by Django 4.1.7 on 2023-03-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_configuration_google_client_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.EmailField(max_length=254)),
                ('phone', models.EmailField(max_length=254)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('city', models.CharField(max_length=254)),
                ('address', models.TextField(blank=True)),
            ],
        ),
    ]
