# Generated by Django 4.1.7 on 2023-03-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_currency_remove_configuration_currency_symbol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='author',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='contact_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='facebook',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='instagram',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='keywords',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='support_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='tiktiok',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='website_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
