# Generated by Django 4.1.7 on 2023-03-16 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_currency_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='exchangerate_api',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
