# Generated by Django 4.1.7 on 2023-03-22 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_banner_description_ar_banner_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.tag'),
        ),
    ]
