# Generated by Django 4.1.7 on 2023-03-22 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_banner_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, upload_to='banner_images/'),
        ),
        migrations.DeleteModel(
            name='BannerImage',
        ),
    ]
