# Generated by Django 4.1.7 on 2023-03-22 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_banner_image_delete_bannerimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='image',
        ),
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='banner_images/')),
                ('banner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.banner')),
            ],
        ),
    ]
