# Generated by Django 4.1.7 on 2023-03-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='email_recivers',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='smtp_SSL',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='smtp_host',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='configuration',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='configuration',
            name='smtp_port',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='configuration',
            name='smtp_username',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='configuration',
            name='telegram_bot_api',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='configuration',
            name='telegram_recivers',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
