# Generated by Django 4.1.7 on 2023-03-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_banner_image_bannerimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='google_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
