# Generated by Django 4.1.7 on 2023-03-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_configuration_email_recivers_configuration_smtp_ssl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='logo_white',
            field=models.ImageField(blank=True, upload_to='logos/'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='smtp_port',
            field=models.IntegerField(default=465),
        ),
    ]
