# Generated by Django 4.1.7 on 2023-03-18 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_order_payment_method'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AddField(
            model_name='configuration',
            name='favicon',
            field=models.FileField(blank=True, upload_to='website_images/'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='logo',
            field=models.ImageField(blank=True, upload_to='website_images/'),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='logo_white',
            field=models.ImageField(blank=True, upload_to='website_images/'),
        ),
    ]
