# Generated by Django 4.1.7 on 2023-03-20 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_order_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='cmi_merchant_id',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='configuration',
            name='cmi_sandbox',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='configuration',
            name='cmi_secret_key',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
